name: smart_farm
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  http: ^1.1.0
  provider: ^6.0.5
  google_fonts: ^6.2.1
  flutter_secure_storage: ^9.2.4
  supabase_flutter: ^2.12.0
  dotenv: ^4.1.0
  shared_preferences: ^2.2.2
  go_router: ^13.0.0
  intl: ^0.19.0
  equatable: ^2.0.5
  fl_chart: ^1.1.1
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.0
  image_picker: ^1.0.7
  path_provider: ^2.1.0
  share_plus: ^7.2.0
  url_launcher: ^6.2.0
  pdf: ^3.11.3
  flutter_timezone: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
